import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Menu } from '@/components/layout/Menu';
import { Footer } from '@/components/layout/Footer';
import { ChatBot } from '@/components/ui/ChatBot';
import './globals.css';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Kotiketju',
	description: 'Generated by create next app',
	icons: {
		icon: '/kotiketju-logo.png',
		shortcut: '/kotiketju-logo.png',
		apple: '/kotiketju-logo.png',
	},
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// Showcase mode - no authentication
	const isLoggedIn = false;
	const userName = undefined;

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${poppins.variable} antialiased`}
				suppressHydrationWarning
			>
				<Menu isLoggedIn={isLoggedIn} userName={userName} />
				{children}
				<Footer />
				<ChatBot />
			</body>
		</html>
	);
}
